name: Node Continuous Integration

on: 
  push:
    branches: [ main ]
    
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 12
          
      - run: npm ci
      - run: npm test
      - run: npm run build
